[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
lib_deps =
  pololu/VL53L1X@^1.3.1
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit SSD1306@^2.5.11
board_build.partitions = partitions_single_app.csv
extra_scripts =
  pre:scripts/generate_scores.py
board_build.embed_files =
  assets/audio_samples/dream_tides_full_mono10k.pcm
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
monitor_speed = 115200
; C3 实际串口会因电脑和 USB 口变化，请先用 `python3 tools/theremin_tool.py ports` 查看
; monitor_port = /dev/cu.usbmodemXXXX
; upload_port = /dev/cu.usbmodemXXXX

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
monitor_speed = 115200
; S3 实际串口会因电脑和 USB 口变化，请先用 `python3 tools/theremin_tool.py ports` 查看
; monitor_port = /dev/cu.usbmodemXXXX
; upload_port = /dev/cu.usbmodemXXXX
board_build.flash_size = 16MB
